name: Nix Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    
    - name: Install Nix
      # You may pin to the exact commit or the version.
      # uses: cachix/install-nix-action@7ab6e7fd29da88e74b1e314a4ae9ac6b5cda3801
      uses: cachix/install-nix-action@v31.8.0

    - name: Build with Nix
      # Build the project with nix flake and creates a new zip 
      run: |
        nix build
        cp -rL --no-preserve=ownership result/* .
        zip -r seekers-api.zip seekers

    - name: Automatic Releases
      if: github.event_name == 'push'
      # You may pin to the exact commit or the version.
      # uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        # GitHub secret token
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        # Git tag (for automatic releases)
        automatic_release_tag: "prerelease" # optional
        # Should this release be marked as a draft?
        draft: false # optional
        # Should this release be marked as a pre-release?
        prerelease: true # optional, default is true
        # Release title (for automatic releases)
        title: "prerelease" # optional
        # Assets to upload to the release
        files: seekers-api.zip # optional
